name: CI
env:
  VSCODE_TOKEN: ${{ secrets.VSCODE_TOKEN }}

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: git checkout master
      - uses: actions/setup-node@v1
      - name: Build and Deploy
        run: |
            npm install lerna -g
            npm install santari -g
            lerna bootstrap
            chmod +x ./scripts/publish.sh
            sh ./scripts/publish.sh
    
