name: CI
env:
  VSCODE_TOKEN: ${{ secrets.VSCODE_TOKEN }}

on:
  push:
    tags:
      - release
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - run: git checkout master
      - name: Build
        uses: actions/setup-node@v3
      - run: |
          npm install lerna -g
          lerna bootstrap --no-ci
      - name: Deploy
        uses: actions/setup-node@v3
      - run: |
          chmod +x ./scripts/publish.sh
          sh ./scripts/publish.sh
        if: github.event == 'release'
