name: CI

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v1
    - name: Build and Deploy
      run: |
        - npm install lerna -g
        - npm install santari -g
        - lerna bootstrap
        - chmod +x ./scripts/publish.sh
        - sh ./scripts/publish.sh
    
